/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cl.duoc.poo.vista;

import cl.duoc.poo.controlador.RegistroPelicula;
import cl.duoc.poo.modelo.Pelicula;
import javax.swing.JOptionPane;

/**
 *
 * @author Ignacio Osorio
 */
public class Registrar extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_registro_pelicula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_titulo_pelicula = new javax.swing.JLabel();
        lbl_duracion = new javax.swing.JLabel();
        lbl_director = new javax.swing.JLabel();
        lbl_anio = new javax.swing.JLabel();
        lbl_genero = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JTextField();
        txt_director = new javax.swing.JTextField();
        txt_anio = new javax.swing.JTextField();
        txt_duracion = new javax.swing.JTextField();
        cbo_genero = new javax.swing.JComboBox<>();
        btn_registrar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        lbl_registro_pelicula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_registro_pelicula.setText("Registro de Película");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("HoytsMarkPlanet");

        lbl_titulo_pelicula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo_pelicula.setText("Título de Película :");

        lbl_duracion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_duracion.setText("Duración (minutos) :");

        lbl_director.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_director.setText("Director :");

        lbl_anio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_anio.setText("Año :");

        lbl_genero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_genero.setText("Género :");

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tituloActionPerformed(evt);
            }
        });

        txt_director.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_directorActionPerformed(evt);
            }
        });

        txt_anio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anioActionPerformed(evt);
            }
        });

        txt_duracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cbo_genero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbo_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genero", "Accion", "Aventura", "Catastrofe", "Ciencia ficcion", "Comedia", "Documentales", "Drama", "Fantasia", "Musicales", "Suspenso", "Terror" }));
        cbo_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_generoActionPerformed(evt);
            }
        });

        btn_registrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_registro_pelicula)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_titulo_pelicula)
                            .addComponent(lbl_director)
                            .addComponent(lbl_anio)
                            .addComponent(lbl_duracion)
                            .addComponent(lbl_genero))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_registrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                                .addComponent(btn_limpiar))
                            .addComponent(txt_director, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_titulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_duracion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_anio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_genero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lbl_registro_pelicula))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_titulo_pelicula))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_director)
                    .addComponent(txt_director, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_anio)
                    .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_duracion)
                    .addComponent(txt_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_genero)
                    .addComponent(cbo_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiar)
                    .addComponent(btn_registrar))
                .addGap(47, 47, 47)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_directorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_directorActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        
        
        
        
        String titulo;
        String director;
        int anio;
        int duracion;
        String genero;
        
        try {
            //idPelicula = generarIdPelicula();
            titulo = this.txt_titulo.getText().trim();
            director = this.txt_director.getText().trim();
            anio = Integer.parseInt(this.txt_anio.getText().trim());
            duracion = Integer.parseInt(this.txt_duracion.getText().trim());
            //anio = this.txt_anio.getText().trim();
            //duracion = this.txt_duracion.getText().trim();
            genero = this.cbo_genero.getSelectedItem().toString();

            if(validarDatos()){
                //Si todos los datos son validados se genera el objeto, y luego se registra en la colección
                Pelicula peli = new Pelicula(0, titulo, director, anio, duracion, genero);
                
                //Agregar pelicula a la colección
                //if(RegistroPelicula.agregarPelicula(peli)){
                  //  JOptionPane.showMessageDialog(this,"Pelicula Registrada en nuestro Sistema","Registro",JOptionPane.INFORMATION_MESSAGE);
                
                //Agregar pelicula a SQL  
                if(RegistroPelicula.agregarPeli(peli)){
                    JOptionPane.showMessageDialog(this,"Pelicula Registrada en nuestro Sistema","Registro",JOptionPane.INFORMATION_MESSAGE);
                    
                }else{
                    JOptionPane.showMessageDialog(this,"Error en el registro de película en la colección","Error de Registro",JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this,"Datos mal ingresados","Alerta",JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (Exception NumberFormatException){
            JOptionPane.showMessageDialog(this,"Favor ingresar dígitos en Año y Duración","Alerta",JOptionPane.WARNING_MESSAGE);
        
        }
        
        limpiarDatos();
        
        
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tituloActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        
        limpiarDatos();
        
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void cbo_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbo_generoActionPerformed

    private void txt_anioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JComboBox<String> cbo_genero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_anio;
    private javax.swing.JLabel lbl_director;
    private javax.swing.JLabel lbl_duracion;
    private javax.swing.JLabel lbl_genero;
    private javax.swing.JLabel lbl_registro_pelicula;
    private javax.swing.JLabel lbl_titulo_pelicula;
    private javax.swing.JTextField txt_anio;
    private javax.swing.JTextField txt_director;
    private javax.swing.JTextField txt_duracion;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables

    private boolean validarDatos(){
        boolean valida_titulo = false;
        boolean valida_director = false;
        boolean valida_anio = false;
        boolean valida_duracion = false;
        boolean valida_genero = false;
        
        
        //Valida titulo de película
        if(this.txt_titulo.getText().trim() == null || this.txt_titulo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese un título de película correcto.","Alerta",JOptionPane.WARNING_MESSAGE);
            valida_titulo = false;
            
        }else{
            valida_titulo = true;
        }
        
        //Valida Director
        if(this.txt_director.getText().trim() == null || this.txt_director.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese un nombre de Director","Alerta",JOptionPane.WARNING_MESSAGE);
            valida_director = false;
        }else{
            valida_director = true;
        }
        
        //Valida año
        if(this.txt_anio.getText().trim() == null || this.txt_anio.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese el año de la Pelicula","Alerta",JOptionPane.WARNING_MESSAGE);
            valida_anio = false;
        }else if(this.txt_anio.getText().length() != 4){
            JOptionPane.showMessageDialog(this,"Ingrese un año válido","Alerta",JOptionPane.WARNING_MESSAGE);
            valida_anio = false;
        }else if(Integer.parseInt(this.txt_anio.getText()) < 1800){
            JOptionPane.showMessageDialog(this,"Ingrese un año mayor a 1800","Alerta",JOptionPane.WARNING_MESSAGE);
            valida_anio = false;
        }else{
            valida_anio = true;
        }
        
        //Valida duracion
        if(this.txt_duracion.getText().trim() == null || this.txt_duracion.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese la duración de la pelicula en minutos","Alerta",JOptionPane.WARNING_MESSAGE);
            valida_duracion = false;
        }else{
            valida_duracion = true;
        }
        
        //Valida genero
        if(this.cbo_genero.getSelectedItem().toString() == null || this.cbo_genero.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(this,"Seleccione un género de película","Alerta",JOptionPane.WARNING_MESSAGE);
            valida_genero = false;
        }else if(this.cbo_genero.getSelectedItem().equals("Genero")){
            JOptionPane.showMessageDialog(this,"Seleccione un género de película","Alerta",JOptionPane.WARNING_MESSAGE);
            valida_genero = false;
        }else{
            valida_genero = true;
        }
        
        return valida_titulo && valida_director && valida_anio && valida_duracion && valida_genero;
        
    }

    /*
    private int generarIdPelicula() {
        
        idPelicula++;

        return idPelicula;
    }
    */
    private void limpiarDatos(){
        txt_anio.setText(null);
        txt_director.setText(null);
        txt_duracion.setText(null);
        txt_titulo.setText(null);
        
        cbo_genero.setSelectedItem("Genero");
    }

}
